# Generated by Django 2.0.5 on 2018-06-01 08:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a currency you prefer to monitor.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular task', primary_key=True, serialize=False)),
                ('price_starts', models.FloatField(help_text='Enter a starting price.(e.g. 1000. This should smaller than ending price)')),
                ('price_ends', models.FloatField(help_text='Enter a ending prince.(e.g. 2000. This should bigger than starting price )')),
                ('target_amount', models.IntegerField(help_text='Enter a target amount(integer only, e.g. 500) to monitor')),
                ('status', models.CharField(blank=True, choices=[('a', 'Active'), ('m', 'Mature'), ('c', 'Completed'), ('d', 'Disable')], default='a', help_text='Task Active', max_length=1)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashing.Task')),
            ],
        ),
    ]
