# Generated by Django 2.0.5 on 2018-06-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='currency',
            field=models.CharField(blank=True, choices=[('btcusd', 'American Dollar'), ('btcaud', 'Australian Dollar'), ('btccad', 'Canadian Dollar'), ('btcgbp', 'English Pound'), ('btceur', 'Euro'), ('btccny', 'Chinese Yuan')], default='btcusd', help_text='Choose a currency you prefer to monitor.', max_length=6),
        ),
    ]
