# Generated by Django 2.0.5 on 2018-06-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashing', '0002_auto_20180601_1834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskInstance',
            new_name='Query',
        ),
    ]
