# Generated by Django 2.0.5 on 2018-06-01 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashing', '0003_auto_20180601_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='time_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='time_mature',
            field=models.DateTimeField(blank=True, help_text='Record mature time for this query', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('s', 'Start'), ('f', 'Finish'), ('p', 'Pending')], default='p', help_text='Task Pending.', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='time_finish',
            field=models.DateTimeField(blank=True, help_text='Time the task finishes', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_start',
            field=models.DateTimeField(blank=True, help_text='Time the task starts', null=True),
        ),
    ]
