# Generated by Django 2.0.5 on 2018-06-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashing', '0005_auto_20180610_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Notification message body', max_length=6)),
                ('time_add', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashing.Query')),
            ],
            options={
                'ordering': ['-time_add'],
            },
        ),
    ]
